spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpaex
    username: root
    password: donghee0326
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      type:
        descriptor:
          sql: true
    properties:
      hibernate:
        format_sql: true